import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";
import { Toaster } from "@/components/ui/sonner";
import SmoothScrolling from "@/components/global/SmoothScrolling";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={` relative ${inter.variable} ${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />

            <SmoothScrolling>
              {children}
              <Footer />
            </SmoothScrolling>
            <Toaster />
          </ThemeProvider>
          {/* <NavBar />  */}
        </body>
      </html>
    </>
  );
}
